/**
 * Opens a print-friendly window for a prescription object.
 */
export function printPrescription(rx, { patientName, doctorName } = {}) {
  const meds = (rx.medicines || [])
    .map(
      (m, i) =>
        `<tr>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0">${i + 1}</td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0">${escapeHtml(m.medicineName || m.name || '')}</td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0">${escapeHtml(m.dosage || '')}</td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0">${escapeHtml(m.frequency || '')}</td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0">${escapeHtml(m.duration || '')}</td>
        </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html><html><head><title>Prescription</title>
    <style>
      body{font-family:Inter,system-ui,sans-serif;color:#0f172a;padding:32px;max-width:720px;margin:0 auto}
      h1{font-size:20px;margin:0 0 4px}
      .muted{color:#64748b;font-size:13px}
      table{width:100%;border-collapse:collapse;margin-top:20px;font-size:13px}
      th{text-align:left;padding:8px;border-bottom:2px solid #0f172a;font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#64748b}
      .footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8}
    </style></head><body>
    <h1>Clinova prescription</h1>
    <p class="muted">Demo clinical document — not for dispensing</p>
    <p style="margin-top:20px"><strong>Patient:</strong> ${escapeHtml(patientName || '—')}<br/>
    <strong>Prescriber:</strong> ${escapeHtml(doctorName || '—')}<br/>
    <strong>Date:</strong> ${rx.createdAt ? new Date(rx.createdAt).toLocaleDateString() : '—'}<br/>
    <strong>Status:</strong> ${escapeHtml(rx.status || 'active')}</p>
    <table><thead><tr><th>#</th><th>Medicine</th><th>Dose</th><th>Frequency</th><th>Duration</th></tr></thead>
    <tbody>${meds || '<tr><td colspan="5" style="padding:12px">No medicines listed</td></tr>'}</tbody></table>
    ${rx.instructions ? `<p style="margin-top:20px"><strong>Instructions</strong><br/>${escapeHtml(rx.instructions)}</p>` : ''}
    <div class="footer">Generated by Clinova portfolio demo · ${new Date().toISOString()}</div>
    <script>window.onload=function(){window.print()}</script>
    </body></html>`;

  const w = window.open('', '_blank', 'noopener,noreferrer,width=800,height=900');
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  return true;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
